(lang dune 3.21)

(name robin)

(generate_opam_files true)

(source
 (github jumbojets/robin))

(authors "James Taylor") 

(maintainers "James Taylor")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name robin)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
